spring.application.name=demo
spring.security.user,name= demo123
spring.security.user.password= demo@123

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb

spring.app.jwtSecret = mySecretKey123!#4546546
spring.app.jwtExpiration = 3000000000
